<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>B</string>
    <key>scopeName</key>
    <string>source.b</string>
    <key>foldingStartMarker</key>
    <string>(\{|\()</string>
    <key>foldingEndMarker</key>
    <string>(\}|\))</string>
    <key>fileTypes</key>
    <array>
      <string>b</string>
    </array>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#comments</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#constants</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#operators</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#scope</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#functions</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#variables</string>
          </dict>
        </array>
      </dict>
      <key>comments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.block.empty.b</string>
            <key>match</key>
            <string>/\*\*/</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.b</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>name</key>
            <string>comment.block.b</string>
            <key>begin</key>
            <string>/\*</string>
            <key>captures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.comment.b</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\*/</string>
          </dict>
        </array>
      </dict>
      <key>constants</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>constant.numeric.b</string>
            <key>match</key>
            <string>\b(?&lt;![\.0-9])([0-9]+)(?![\.0-9])\b</string>
          </dict>
        </array>
      </dict>
      <key>operators</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.operator.logical.b</string>
            <key>match</key>
            <string>!(?!=)</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.bitwise.b</string>
            <key>match</key>
            <string>&lt;&lt;|&gt;&gt;|&amp;|\|</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.relational.b</string>
            <key>match</key>
            <string>&lt;=|&gt;=|&lt;|&gt;</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.comparison.b</string>
            <key>match</key>
            <string>==|!=</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.arithmetic.b</string>
            <key>match</key>
            <string>--|\+\+|(?&lt;!/)\*\*|(?&lt;!\*)/(?!/|\*)|%|\*(?&lt;!/\*)(?!/([^\*]|$))|\+|-</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.assignment.b</string>
            <key>match</key>
            <string>(=&gt;|(=(?!(=))))</string>
          </dict>
          <dict>
            <key>comment</key>
            <string>keyword.operator.ternary.b</string>
            <key>begin</key>
            <string>\?</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <array>
                <dict>
                  <key>name</key>
                  <string>keyword.operator.ternary.b</string>
                </dict>
              </array>
            </dict>
            <key>end</key>
            <string>\:</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <array>
                <dict>
                  <key>name</key>
                  <string>keyword.operator.ternary.b</string>
                </dict>
              </array>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#constants</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#operators</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#strings</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functions</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#variables</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.b</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.b</string>
                <key>match</key>
                <string>(\*[0net\(\)\*\"\'])|(\%[scdo])</string>
              </dict>
            </array>
          </dict>
          <dict>
            <key>name</key>
            <string>string.quoted.single.b</string>
            <key>begin</key>
            <string>'</string>
            <key>end</key>
            <string>'</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.b</string>
                <key>match</key>
                <string>(\*[0net\(\)\*\"\'])|(\%[scdo])</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.b</string>
            <key>match</key>
            <string>(?&lt;=^|[\s\{\}\;\:]|\*\/)(goto|if|else|switch|case|default|break|while|return)\b</string>
          </dict>
        </array>
      </dict>
      <key>scope</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.primitive.b</string>
            <key>match</key>
            <string>(?&lt;=^|[^@\w\.])(extrn|auto)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>entity.name.type.b</string>
            <key>match</key>
            <string>\b([A-Z]+\w*)\b</string>
          </dict>
        </array>
      </dict>
      <key>functions</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.function.b</string>
            <key>match</key>
            <string>(?&lt;![\)\@\.\$\#\`\"'\]\\\~\^\w])([_A-Za-z]\w*)(?=\s*\()</string>
          </dict>
        </array>
      </dict>
      <key>variables</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>variable.other.b</string>
            <key>match</key>
            <string>\b([_a-z]+\w*)\b</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
